image: mcr.microsoft.com/playwright:focal

stages:
  - test

e2e:
  stage: test
  script:
    - cd docs/
    - npm install playwright
    - npm install @playwright/test
    - npx playwright test
  retry:
    max: 2
    when:
    - runner_system_failure
  only:
    - web
  artifacts:
    when: always
    name: "results"
    paths:
      - docs/*
    exclude:
      - docs/testcodes/*
      - docs/node_modules/*
      - docs/*.ts
